### ISSUE TITLE
Gather running when calling in api

### ISSUE THREAD

**Issue by flt6** [flt6/tts_rebuild#2]
```python
Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\client.py", line 138, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "F:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "F:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\http.py", line 194, in read_line
    line = await stream.readline()
  File "F:\ProgramData\Anaconda3\lib\asyncio\streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "F:\ProgramData\Anaconda3\lib\asyncio\streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "F:\ProgramData\Anaconda3\lib\asyncio\streams.py", line 517, in _wait_for_data
    await self._waiter
  File "F:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "F:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 328, in __wakeup
    future.result()
  File "F:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "F:\ProgramData\Anaconda3\lib\asyncio\sslproto.py", line 703, in _process_write_backlog
    del self._write_backlog[0]
IndexError: deque index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\TEMP\**\**\mytts\speech.py", line 50, in _wait
    self._ret = loop.run_until_complete(self._task)
  File "C:\Users\****\AppData\Roaming\Python\Python39\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "F:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "F:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 256, in __step
    result = coro.send(None)
  File "e:\TEMP\**\**\mytts\tts.py", line 60, in implete
    async with client.connect(endpoint2,extra_headers={'Origin':'https://azure.microsoft.com'}) as websocket:
  File "F:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\client.py", line 642, in __aenter__
    return await self
  File "F:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "F:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
  File "F:\ProgramData\Anaconda3\lib\asyncio\futures.py", line 201, in result
    raise self._exception
  File "F:\ProgramData\Anaconda3\lib\asyncio\tasks.py", line 258, in __step
    result = coro.throw(exc)
  File "F:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "F:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\client.py", line 326, in handshake
    status_code, response_headers = await self.read_http_response()
  File "F:\ProgramData\Anaconda3\lib\site-packages\websockets\legacy\client.py", line 144, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
```

Error occurred in https://github.com/flt6/Read_tts/commit/aecf3a8fda118fad3e0e19e99b68c3d947d22c09

**Comment by flt6** [comment]
nearly fixed 1af3f8f63178d1713e06fe65f1a49c806966ae9e
